<?php

namespace AppBundle\Repository;

/**
 * FosUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FosUserRepository extends \Doctrine\ORM\EntityRepository
{
}
