<?php

namespace AppBundle\Repository;

/**
 * GratItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GratItemRepository extends \Doctrine\ORM\EntityRepository
{
}
