<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * GratDateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GratDateRepository extends EntityRepository
{

	public function fetch($where_params = null, $order_by = "") {

		$em = $this->getEntityManager();

		$where = "WHERE 1=1";
		foreach ($where_params as $field => $value) {
			$where .= " AND gd." . $field . " = '" . $value . "'";
		}

		$sql = "SELECT gd 
					FROM AppBundle:GratDate gd
				$where
				$order_by";

		$result = $em->createQuery($sql)->getResult();

		return $result;


	}


}
