<?php

namespace AppBundle\Repository;

/**
 * GratDateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GratDateRepository extends \Doctrine\ORM\EntityRepository
{
}
